### ISSUE TITLE
Do you know site builder drag and drop

### ISSUE THREAD

**Issue by vahidalvandi** [xcomptek/awesome-saas-boilerplates#33]
Hello
Do you know site builder drag and drop with react in saas boilerplate?

**Comment by filip-cermak** [comment]
Hello,
I believe that [Divjoy offers drag-and-drop](https://app.startupguns.com/api/link/divjoy/github) functionality. However, some coding will still be necessary. You can filter the templates based on features here: [https://startupguns.com/](https://startupguns.com/). Please let me know if I can assist you further. :)
