### ISSUE TITLE
Misinformation?

### ISSUE THREAD

**Issue by CodeCubeNeo** [xcomptek/awesome-saas-boilerplates#96]
Electrik - Saas Starter Kit --- its free and open source
The SaaS boilerplate by Apptension (+React) --- also free and open source
maybe add a paid/free tag to all of them *just like if its open source or not

**Comment by smirnov-am** [comment]
could you please open a PR?

**Comment by smirnov-am** [comment]
added free/paid on https://xcomptek.com/awesome-saas-boilerplates/
